baseurl = "/"
relativeurls = true
publishDir = "../docs"
hasCJKLanguage = true
languageCode = "ja-jp"
title = "VISDOM"
author = "SUGIMOTO Tatsuo"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-83804663-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/sugi2000/visdom"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/visdomjp"

[params]
    description = "VISDOM: DataVis information website."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml", "js"]
    highlightjsTheme = "github"
    
    # logo = "images/logo.png"
    copyright = "visdom"
    twitter = "https://twitter.com/visdomjp"
    facebook = "https://www.facebook.com/visdom.jp"
    github = "https://github.com/sugi2000"
    email = "sugi2000@gmail.com"
    analytics = "UA-83804663-1"
    
    [params.logo]
    url = "logo.jpg"
    width = 50
    height = 50
    alt = "Logo"

